//
//  Texts.swift
//  Medfast
//
//  Created by Vladislav on 15.11.2023.
//

import Foundation

enum Texts {
    enum Onboarding {
        static let firstViewText = NSLocalizedString("Book an appointment with the right doctor", comment: "")
        static let secondViewText = NSLocalizedString("Your Medicine in your hand Anytime - Anywere", comment: "")
        static let thirdViewText = NSLocalizedString("Lab tests at home. Doorstep to collect your sample", comment: "")
        static let skip = NSLocalizedString("Skip", comment: "")
        static let next = NSLocalizedString("Next", comment: "")
        static let getStarted = NSLocalizedString("Get started", comment: "")
        static let signIn = NSLocalizedString("Sign in", comment: "")
    }

    enum Login {
        static let header = NSLocalizedString("Welcome to Medfast!", comment: "")
        static let title = NSLocalizedString("We happy to see you! To use your account, you should log in first", comment: "")
        static let login = NSLocalizedString("Log In", comment: "")
        static let loginErrorMessage = NSLocalizedString("We cannot find an account with this email address", comment: "")
        static let emailAdress = NSLocalizedString("Email Address", comment: "")
        static let emailPlaceholder = NSLocalizedString("Name@gmail.com", comment: "")
        static let emailAdressError = NSLocalizedString("Please enter valid email address", comment: "")
        static let password = NSLocalizedString("Password", comment: "")
        static let passwordPlaceholder = NSLocalizedString("Enter password", comment: "")
        static let passwordError = NSLocalizedString("Please enter valid password address", comment: "")
        static let forgotPassword = NSLocalizedString("Forgot your password?", comment: "")
        static let dontHaveAnAccount = NSLocalizedString("Don't have an account?", comment: "")
        static let register = NSLocalizedString("Register", comment: "")
    }

    enum ForgotYourPassword {
        static let forgotPasswordHeader = NSLocalizedString("Forgot Your Password?", comment: "")
        static let forgotPasswordTitle = NSLocalizedString("Please enter your email address. We will send a code to change your password", comment: "")
        static let backTo = NSLocalizedString("Back to", comment: "")
        static let singIn = NSLocalizedString("Sing in", comment: "")
        static let emailAdress = NSLocalizedString("Email Address", comment: "")
        static let enterEmail = NSLocalizedString("Enter Email", comment: "")
        static let sendCode = NSLocalizedString("Send Code", comment: "")
        static let checkYourEmailHeader = NSLocalizedString("Check your email", comment: "")
        static let checkYourEmailTitle = NSLocalizedString("We emailed a confirmation code with 4 numbers  to user.email@gmail.com", comment: "")
        static let resendCode = NSLocalizedString("Resend Code", comment: "")
        static let verify = NSLocalizedString("Verify", comment: "")
    }

    enum SetNewPassword {
        static let header = NSLocalizedString("Set new password", comment: "")
        static let title = NSLocalizedString("Please enter your new password", comment: "")
        static let newPassword = NSLocalizedString("New Password", comment: "")
        static let repeatPassword = NSLocalizedString("Repeat password", comment: "")
        static let setAndLogin = NSLocalizedString("Set and login", comment: "")
        static let backTo = NSLocalizedString("Back to", comment: "")
        static let singIn = NSLocalizedString("Sing in", comment: "")
    }
    
    enum Registration {
        static let back = NSLocalizedString("Back", comment: "")
        static let next = NSLocalizedString("Next", comment: "")
        static let reset = NSLocalizedString("Reset", comment: "")
        static let done = NSLocalizedString("Done", comment: "")
        static let completeRegistration = NSLocalizedString("Complete Registration", comment: "")
        static let cancelRegistration = NSLocalizedString("Cancel registration", comment: "")
        static let backToSignUp = NSLocalizedString("Back to Sign Up", comment: "")
        static let termsAndConditions = NSLocalizedString("Terms and Conditions", comment: "")
        static let termsAndConditionsCheckbox = NSLocalizedString("By clicking the \"Register\" button, you agree to our Terms and Conditions", comment: "")
        static let registration = NSLocalizedString("Registration", comment: "")
        static let enterYourCredentials = NSLocalizedString("Please enter your credentials to proceed", comment: "")
        static let personalDetails = NSLocalizedString("Personal Details", comment: "")
        static let name = NSLocalizedString("name", comment: "")
        static let namePlaceholder = NSLocalizedString("Your name", comment: "")
        static let surname = NSLocalizedString("Surname", comment: "")
        static let surnamePlaceholder = NSLocalizedString("Your surname", comment: "")
        static let dateOfBirth = NSLocalizedString("Date of birth", comment: "")
        static let dateOfBirthPlaceholder = NSLocalizedString("MM/DD/YYYY", comment: "")
        static let address = NSLocalizedString("Address", comment: "")
        static let street = NSLocalizedString("Street", comment: "")
        static let streetPlaceholder = NSLocalizedString("Your street", comment: "")
        static let house = NSLocalizedString("House", comment: "")
        static let housePlaceholder = NSLocalizedString("Your house", comment: "")
        static let apartment = NSLocalizedString("Apartment", comment: "")
        static let apartmentPlaceholder = NSLocalizedString("Your apartment", comment: "")
        static let city = NSLocalizedString("City", comment: "")
        static let cityPlaceholder = NSLocalizedString("Your city", comment: "")
        static let state = NSLocalizedString("State", comment: "")
        static let statePlaceholder = NSLocalizedString("Your state", comment: "")
        static let zip = NSLocalizedString("ZIP", comment: "")
        static let zipPlaceholder = NSLocalizedString("xxxx", comment: "")
        static let contacts = NSLocalizedString("Contacts", comment: "")
        static let email = NSLocalizedString("Email Address", comment: "")
        static let emailPlaceholder = NSLocalizedString("Name@gmail.com", comment: "")
        static let phone = NSLocalizedString("Phone number", comment: "")
        static let phonePlaceholder = NSLocalizedString("+1(xxx) xxx xxx", comment: "")
        static let personalDetailsPlaceholder = NSLocalizedString("Personal Details", comment: "")
        static let legalSex = NSLocalizedString("Legal sex", comment: "")
        static let female = NSLocalizedString("Female", comment: "")
        static let male = NSLocalizedString("Male", comment: "")
        static let choose = NSLocalizedString("Choose bot to disclose", comment: "")
        static let citizenship = NSLocalizedString("Citizenship", comment: "")
        static let citizenshipPlaceholder = NSLocalizedString("Choose from options", comment: "")
        static let password = NSLocalizedString("Password", comment: "")
        static let newPassword = NSLocalizedString("New password", comment: "")
        static let passwordPlaceholder = NSLocalizedString("New password", comment: "")
        static let repeatPassword = NSLocalizedString("Repeat password", comment: "")
        static let repeatPlaceholder = NSLocalizedString("Repeat password", comment: "")
    }
    
    enum ConfirmRegistration {
        static let header = NSLocalizedString("Please confirm your email address", comment: "")
        static let text = NSLocalizedString("Thanks for signing up to Medfast. We’re happy to have you with us. Please check your email to verify your account", comment: "")
        static let goToSignUp = NSLocalizedString("Go to sign in", comment: "")
    }

    enum termsAndConditions {
        static let termsAndConditions = NSLocalizedString("Terms and Conditions", comment: "")
        static let termAndConditionUpdate = NSLocalizedString("Last updated:", comment: "")
        static let iHaveAgreed = NSLocalizedString("I’ve agreed with this", comment: "")
    }

    enum PopUpsTexts {
        static let cantFindAnAccount = NSLocalizedString("We cannot find an account with this email address", comment: "")
        static let somethingWentWrong = NSLocalizedString("Something went wrong! Please try again later.", comment: "")
        static let passwordSuccessfullyChanged = NSLocalizedString("Password has been successfully changed.", comment: "")
        static let newPasswordMustBeTheSame = NSLocalizedString("Passwords must be the same", comment: "")
        static let newPasswordCantBeTheSame = NSLocalizedString("The new password cannot be the same as the old one.", comment: "")
        static let codeIsWrong = NSLocalizedString("Code is wrong", comment: "")
        static let uploadFileError = NSLocalizedString("Upload a file with the following extensions: jpg, gif, png, jpeg.", comment: "")
        static let appointmentWasSuccessfully = NSLocalizedString("Your appointment was successfully confirmed", comment: "")
    }

    enum PatientHomePage {
        static let hello = NSLocalizedString("Hello", comment: "")
        static let searchPlaceholder = NSLocalizedString("Find a doctor or service", comment: "")
        static let searchPlaceholderEmptyState = NSLocalizedString("Find a doctor", comment: "")
        static let visits = NSLocalizedString("Visits", comment: "")
        static let tests = NSLocalizedString("Test", comment: "")
        static let prescriptions = NSLocalizedString("Prescriptions", comment: "")
        static let upcomingVisits = NSLocalizedString("Upcoming visits", comment: "")
        static let pastVisits = NSLocalizedString("Past visits", comment: "")
        static let makeAnAppointment = NSLocalizedString("Make an appointment", comment: "")
        static let createAnAppointment = NSLocalizedString("You haven't upcoming visits. Created an appointment for today", comment: "")
        static let thereWillBeATeam = NSLocalizedString("There will be a team of doctor assigned to you", comment: "")
        static let seeHistory = NSLocalizedString("See history", comment: "")
        static let viewAll = NSLocalizedString("View all", comment: "")
        static let viewDetails = NSLocalizedString("View details", comment: "")
        static let yourCareTeam = NSLocalizedString("Your care team", comment: "")
        static let recommendations = NSLocalizedString("Recommendations", comment: "")
        static let view = NSLocalizedString("View", comment: "")
        static let edit = NSLocalizedString("Edit", comment: "")
        static let reschedule = NSLocalizedString("Reschedule", comment: "")
        static let cancel = NSLocalizedString("Cancel", comment: "")
    }

    enum SlideMenu {
        static let profile = NSLocalizedString("Profile", comment: "")
        static let billingSettings = NSLocalizedString("Billing Settings", comment: "")
        static let settings = NSLocalizedString("Settings", comment: "")
        static let logOut = NSLocalizedString("Log out", comment: "")
    }
    
    enum PaymentSettings {
        static let back = NSLocalizedString("Back", comment: "")
        static let edit = NSLocalizedString("Edit", comment: "")
        static let delete = NSLocalizedString("Delete", comment: "")
        static let paymentSettings = NSLocalizedString("Payment settings", comment: "")
        static let cardsDetails = NSLocalizedString("Cards Details", comment: "")
        static let manageYourCards = NSLocalizedString("Manage your cards and preferences here", comment: "")
        static let addNewPaymentMethod = NSLocalizedString("Add new payment method", comment: "")
        static let selectDefaultPaymentMethod = NSLocalizedString("Select default payment method", comment: "")
        static let contactEmail = NSLocalizedString("Contact email", comment: "")
        static let whereInvoicesSent = NSLocalizedString("Where should the invoices be sent?", comment: "")
        static let sendToEmail = NSLocalizedString("Send to my email", comment: "")
        static let sendToSpecifiedEmail = NSLocalizedString("Send to specified email", comment: "")
        static let specifiedEmailPlaceholder = NSLocalizedString("Email address", comment: "")
        static let editDetails = NSLocalizedString("Edit details", comment: "")
        static let provideUpdates = NSLocalizedString("Please provide updates", comment: "")
        static let cardNumber = NSLocalizedString("Card number", comment: "")
        static let cardNumberPlaceholder = NSLocalizedString("0000 0000 0000 0000", comment: "")
        static let cardHolder = NSLocalizedString("Card Holder", comment: "")
        static let cardHolderPlaceholder = NSLocalizedString("Enter cardholder’s full name", comment: "")
        static let date = NSLocalizedString("Date", comment: "")
        static let datePlaceholder = NSLocalizedString("MM/YY", comment: "")
        static let cvc = NSLocalizedString("CVC", comment: "")
        static let cvcPlaceholder = NSLocalizedString("000", comment: "")
        static let provideInformation = NSLocalizedString("Please provide information", comment: "")
        static let addNewCardNumberPlaceholder = NSLocalizedString("**** **** **** ****", comment: "")
        static let addNewCardValidityPlaceholder = NSLocalizedString("**/20**", comment: "")
        static let nameSurname = NSLocalizedString("NAME SURNAME", comment: "")
    }

    enum Profile {
        static let cancel = NSLocalizedString("Cancel", comment: "")
        static let save = NSLocalizedString("Save", comment: "")
        static let name = NSLocalizedString("name", comment: "")
        static let namePlaceholder = NSLocalizedString("Your name", comment: "")
        static let surname = NSLocalizedString("Surname", comment: "")
        static let surnamePlaceholder = NSLocalizedString("Your surname", comment: "")
        static let dateOfBirth = NSLocalizedString("Date of birth", comment: "")
        static let dateOfBirthPlaceholder = NSLocalizedString("MM/DD/YYYY", comment: "")
        static let legalSex = NSLocalizedString("Legal sex", comment: "")
        static let female = NSLocalizedString("Female", comment: "")
        static let male = NSLocalizedString("Male", comment: "")
        static let choose = NSLocalizedString("Choose bot to disclose", comment: "")
        static let takePhoto = NSLocalizedString("Take a new photo", comment: "")
        static let choosePhoto = NSLocalizedString("Choose from gallery", comment: "")
        static let deletePhoto = NSLocalizedString("Delete photo", comment: "")
        static let address = NSLocalizedString("Address", comment: "")
        static let street = NSLocalizedString("Street Address", comment: "")
        static let streetPlaceholder = NSLocalizedString("Your street", comment: "")
        static let house = NSLocalizedString("House", comment: "")
        static let housePlaceholder = NSLocalizedString("Your house", comment: "")
        static let apartment = NSLocalizedString("Apartment", comment: "")
        static let apartmentPlaceholder = NSLocalizedString("Your apartment", comment: "")
        static let city = NSLocalizedString("City", comment: "")
        static let cityPlaceholder = NSLocalizedString("Your city", comment: "")
        static let state = NSLocalizedString("State", comment: "")
        static let statePlaceholder = NSLocalizedString("Your state", comment: "")
        static let zip = NSLocalizedString("ZIP", comment: "")
        static let zipPlaceholder = NSLocalizedString("xxxx", comment: "")
        static let contacts = NSLocalizedString("Contacts", comment: "")
        static let email = NSLocalizedString("Email Address", comment: "")
        static let emailPlaceholder = NSLocalizedString("Name@gmail.com", comment: "")
        static let phone = NSLocalizedString("Phone number", comment: "")
        static let phonePlaceholder = NSLocalizedString("+1(xxx) xxx xxx", comment: "")
        static let citizenship = NSLocalizedString("Citizenship", comment: "")
        static let citizenshipPlaceholder = NSLocalizedString("Choose from options", comment: "")
    }
    
    enum NewAppointment {
        static let next = NSLocalizedString("Next", comment: "")
        static let book = NSLocalizedString("Book", comment: "")
        static let saveChanges = NSLocalizedString("Save Changes", comment: "")
        static let noSave = NSLocalizedString("No, save", comment: "")
        static let yesCancel = NSLocalizedString("Yes, cancel", comment: "")
        static let scheduleNew = NSLocalizedString("Schedule new", comment: "")
        static let goToHomePage = NSLocalizedString("Go to home page", comment: "")
        static let confirm = NSLocalizedString("Confirm", comment: "")
        static let confirmVisit = NSLocalizedString("Confirm Visit", comment: "")
        static let scheduled = NSLocalizedString("Scheduled", comment: "")
        static let scheduledConfirmed = NSLocalizedString("Scheduled Confirmed", comment: "")
        static let inConsultation = NSLocalizedString("In-Consultation", comment: "")
        static let completed = NSLocalizedString("Completed", comment: "")
        static let missed = NSLocalizedString("Missed", comment: "")
        static let visitNotes = NSLocalizedString("Visit Notes", comment: "")
        static let afterVisitSummary = NSLocalizedString("After visit summary", comment: "")
        static let cancel = NSLocalizedString("Cancel", comment: "")
        static let close = NSLocalizedString("Close", comment: "")
        static let reschedule = NSLocalizedString("Reschedule", comment: "")
        static let viewAppointment = NSLocalizedString("View Appointment", comment: "")
        static let editAppointment = NSLocalizedString("Edit appointment", comment: "")
        static let tryAgain = NSLocalizedString("Try Again", comment: "")
        static let failed = NSLocalizedString("Oops Failed!", comment: "")
        static let failMessage = NSLocalizedString("Appointment failed. Please check your internet connection then try again.", comment: "")
        static let congratulations = NSLocalizedString("Congratulations!", comment: "")
        static let appointmentBooked = NSLocalizedString("Your appointment was booked", comment: "")
        static let appointmentBookedMessage = NSLocalizedString("Good afternoon! We inform you about the booked visit to the ", comment: "")
        static let ifYouDidNotSignUp = NSLocalizedString("If you did not sign up for this account you can ignore this email", comment: "")
        static let appointmentSuccessfully = NSLocalizedString("Appointment successfully booked. You will receive a notification and the doctor you selected will contact you", comment: "")
        static let contactInfoMessage = NSLocalizedString("Problems or questions? Call us +1 (123) 348-2626 or email hello@gmail.com", comment: "")
        static let confirmAppointment = NSLocalizedString("Please confirm your appointment", comment: "")
        static let cancelAppointmentHeader = NSLocalizedString("Are you sure you want to cancel the appointment?", comment: "")
        static let cancelAppointmentMessage = NSLocalizedString("Your visit will be cancelled. The doctor will receive a notice to cancel the visit", comment: "")
        static let appointmentWasCancelledHeader = NSLocalizedString("Appointment was cancelled", comment: "")
        static let appointmentWasCancelledMessage = NSLocalizedString("Your appointment was successfully cancelled. Would you like to schedule a new appointment?", comment: "")
        static let applyFilter = NSLocalizedString("Apply filter", comment: "")
        static let results = NSLocalizedString("Results", comment: "")
        static let resultNotFound = NSLocalizedString("The result has not been found", comment: "")
        static let changeYourQuery = NSLocalizedString("Please change your query or reduce the amount of filters", comment: "")
        static let otherwiseEnterName = NSLocalizedString("* otherwise enter a name", comment: "")
        static let checkError = NSLocalizedString("* check if there is an error", comment: "")
        static let lookSomethingSimilar = NSLocalizedString("look for something similar", comment: "")
        static let timeslotNotAvailable = NSLocalizedString("The timeslot is not available, please choose another time", comment: "")
        static let appointmentCancelledHeader = NSLocalizedString("Your appointment was cancelled", comment: "")
        static let appointmentCancelledMessage = NSLocalizedString("Good afternoon! We inform you about cancelled visit to the", comment: "")
        static let appointmentRescheduledHeader = NSLocalizedString("Your appointment was rescheduled", comment: "")
        static let appointmentRescheduledMessage = NSLocalizedString("We inform you about rescheduled visit to the", comment: "")
        static let specialization = NSLocalizedString("Specialization", comment: "")
        static let availability = NSLocalizedString("Availability", comment: "")
        static let availabilityForToday = NSLocalizedString("Availability for today", comment: "")
        static let availabilityForTomorrow = NSLocalizedString("Availability for tomorrow", comment: "")
        static let availabilityThisWeek = NSLocalizedString("Availability during this week", comment: "")
        static let onlineConsultation = NSLocalizedString("Online consultation", comment: "")
        static let header = NSLocalizedString("Choose type of appointment", comment: "")
        static let visit = NSLocalizedString("Visit", comment: "")
        static let upcomingVisit = NSLocalizedString("Upcoming Visit", comment: "")
        static let pastVisit = NSLocalizedString("Past Visit", comment: "")
        static let test = NSLocalizedString("Test", comment: "")
        static let timeAndDate = NSLocalizedString("Time and Date", comment: "")
        static let visitTime = NSLocalizedString("Visit time", comment: "")
        static let selectDateAndTime = NSLocalizedString("Please select a date and time from the available options", comment: "")
        static let generalInformation = NSLocalizedString("General Information", comment: "")
        static let type = NSLocalizedString("Type", comment: "")
        static let generalInformationDateAndTime = NSLocalizedString("Date & Time", comment: "")
        static let location = NSLocalizedString("Location", comment: "")
        static let hospitalLocation = NSLocalizedString("Location of hospital", comment: "")
        static let duration = NSLocalizedString("Duration", comment: "")
        static let doctor = NSLocalizedString("Doctor", comment: "")
        static let doctors = NSLocalizedString("Doctors", comment: "")
        static let doctorSpecialty = NSLocalizedString("Doctor's specialty", comment: "")
        static let service = NSLocalizedString("Service", comment: "")
        static let typeOfService = NSLocalizedString("Type of Service", comment: "")
        static let selectSpecialist = NSLocalizedString("Please select a specialist from the available options", comment: "")
        static let searchDoctorPlaceholder = NSLocalizedString("Find doctor", comment: "")
        static let searchDoctorAndSpecializationPlaceholder = NSLocalizedString("Find doctor or specialization", comment: "")
        static let availableSpecialists = NSLocalizedString("Available specialists", comment: "")
        static let searchLocationPlaceholder = NSLocalizedString("Find a location", comment: "")
        static let availableLocations = NSLocalizedString("Available locations", comment: "")
        static let searchSpecializationPlaceholder = NSLocalizedString("Find a Specialization", comment: "")
    }
    
    enum Error {
        static let invalidEmailFormat = NSLocalizedString("Invalid e-mail format.", comment: "")
        static let invalidPasswordFormat = NSLocalizedString("Invalid password format.", comment: "")
        static let unknownError = NSLocalizedString("Unknown error", comment: "")
    }
}



